url: https://y7kim.github.io
baseurl: /agency-jekyll-theme

# Site settings
title: Hue & Ai Paper and Tools
email: hueandai@outlook.com
description: "Online home of Hue & Ai Paper and Tools"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
  #  url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://facebook.com/hueandai
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  - title: instagram 
    url: https://instagram.com/hueandai
  #- title: github
  #  url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
# address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
